name: barkeeper
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: "^3.7.2"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # BLE + Barcode
  flutter_reactive_ble: ^5.4.0
  mobile_scanner: ^6.0.10

  # Database (Drift)
  drift: ^2.26.0
  sqlite3_flutter_libs: ^0.5.32

  # Secure storage
  flutter_secure_storage: ^9.2.4

  # State management & DI
  riverpod: ^2.6.1
  get_it: ^8.0.3

  # CSV export & file I/O
  csv: ^6.0.0
  path_provider: ^2.1.5
  share_plus: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Drift codegen
  drift_dev: ^2.26.0
  build_runner: ^2.4.15
